package:
  name: dgllife{{ environ.get('APP_PACKAGE_SUFFIX', '') }}
  version: "0.2.5"

source:
  url: https://files.pythonhosted.org/packages/3b/0e/493a20eb0a9cb08a2647b701232cfe76f3f950b1f5bb3c36c72163f4e30b/dgllife-0.2.5.tar.gz
  sha256: 03fb2051f349cdf1cefa17fcfb089a53fd310e107cdd6b3e444718464c69965e

channels:
  - defaults
  - conda-forge

requirements:
  build:
    - python {{ python }}
    - setuptools
    - cmake
    - git
    - cython
  run:
    - python
    - requests
    - scikit-learn
    - pandas
    - tqdm
    - numpy
    - scipy
    - networkx

about:
  license: Apache